version: 2.1

workflows:
  version: 1
  build-test-and-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
        name: install dependencies
        command: npm run test

  build:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
        name: build
        command: npm run build       